github.com:
    users:
        Assis-Mohanty:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Assis-Mohanty
